### ISSUE TITLE
The question related to TensorRT-CenterNet ‘createConcatPlugin’

### ISSUE THREAD

**Issue by dongkaizhou** [jaemin93/PRML_study#1]
Hi,
Saw your reply for TensorRT-CenterNet ‘createConcatPlugin’,  https://github.com/CaoWGG/TensorRT-CenterNet/issues/51
The link you provided seems to be invalid, can you provide it again?
I am sorry to interrupt you, Thanks.

**Comment by dongkaizhou** [comment]
![企业微信截图_20201106180821](https://user-images.githubusercontent.com/51732836/98354007-1ae10780-205b-11eb-8983-7c25dd3c2cd9.png)

**Comment by jaemin93** [comment]
Hold on a minute, please.
